name: Start Docker Image CI

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  pull-and-run-docker-image:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: pull docker image
      run: docker pull vovantrong/social-server:main
      
    - name: stop docker container
      run: docker stop social-server || true && docker rm social-server || true
      
    - name: run docker image
      run: docker run -p 8080:8080/tcp -d --name social-server vovantrong/social-server:main
