name: Run Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  pull-and-run-docker-image:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: pull docker image
      run: sudo docker pull vovantrong/social-server:main
      
    - name: stop docker container
      run: sudo docker stop social-server || true && sudo docker rm social-server || true
      
    - name: run docker image
      run: sudo docker run -p 8080:8080/tcp -d -n social-server vovantrong/social-server:main
